// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQcbEgIpMSL9V4xHbtjqyYiHbyB-d9kbw',
    appId: '1:946817765720:web:7980d6db201e4a3c77152d',
    messagingSenderId: '946817765720',
    projectId: 'notes-18548',
    authDomain: 'notes-18548.firebaseapp.com',
    storageBucket: 'notes-18548.firebasestorage.app',
    measurementId: 'G-JGPDMG5W9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhgbMDOi4HFVIK8nPpgD_XP5PWGJ0f48o',
    appId: '1:946817765720:android:c59e0e0002fe132b77152d',
    messagingSenderId: '946817765720',
    projectId: 'notes-18548',
    storageBucket: 'notes-18548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqy_YoQ2GVl2ummLWbjYV-xRWvRyZBMAw',
    appId: '1:946817765720:ios:3b95d9e38fe46b7477152d',
    messagingSenderId: '946817765720',
    projectId: 'notes-18548',
    storageBucket: 'notes-18548.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqy_YoQ2GVl2ummLWbjYV-xRWvRyZBMAw',
    appId: '1:946817765720:ios:3b95d9e38fe46b7477152d',
    messagingSenderId: '946817765720',
    projectId: 'notes-18548',
    storageBucket: 'notes-18548.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQcbEgIpMSL9V4xHbtjqyYiHbyB-d9kbw',
    appId: '1:946817765720:web:71bff66ddd2f00fc77152d',
    messagingSenderId: '946817765720',
    projectId: 'notes-18548',
    authDomain: 'notes-18548.firebaseapp.com',
    storageBucket: 'notes-18548.firebasestorage.app',
    measurementId: 'G-G90CVR94LH',
  );
}
