// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxtzSV65EeNrg1jTCUiOuwAzfL2wldsM',
    appId: '1:559045140208:web:041c6d727b36e1a15e6c35',
    messagingSenderId: '559045140208',
    projectId: 'notes-app-32e1a',
    authDomain: 'notes-app-32e1a.firebaseapp.com',
    storageBucket: 'notes-app-32e1a.firebasestorage.app',
    measurementId: 'G-9QPDMVJGH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo7S1FR6qtqXLYiOEiyNFTatTDRxNd7Rg',
    appId: '1:559045140208:android:c24406637c9a45fd5e6c35',
    messagingSenderId: '559045140208',
    projectId: 'notes-app-32e1a',
    storageBucket: 'notes-app-32e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6tcPHlcR0s40HaNBfPEIWK9n4WaXRNTs',
    appId: '1:559045140208:ios:34f1de18dc25fcb55e6c35',
    messagingSenderId: '559045140208',
    projectId: 'notes-app-32e1a',
    storageBucket: 'notes-app-32e1a.firebasestorage.app',
    iosClientId: '559045140208-o62aglk90vdn9beksuh880gk2qtockfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6tcPHlcR0s40HaNBfPEIWK9n4WaXRNTs',
    appId: '1:559045140208:ios:34f1de18dc25fcb55e6c35',
    messagingSenderId: '559045140208',
    projectId: 'notes-app-32e1a',
    storageBucket: 'notes-app-32e1a.firebasestorage.app',
    iosClientId: '559045140208-o62aglk90vdn9beksuh880gk2qtockfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXxtzSV65EeNrg1jTCUiOuwAzfL2wldsM',
    appId: '1:559045140208:web:c413eb204a54b9125e6c35',
    messagingSenderId: '559045140208',
    projectId: 'notes-app-32e1a',
    authDomain: 'notes-app-32e1a.firebaseapp.com',
    storageBucket: 'notes-app-32e1a.firebasestorage.app',
    measurementId: 'G-GVS5DNLDN4',
  );

}